import 'package:flutter/material.dart';

void main() {
  runApp(const AldujaApp());
  }

  class AldujaApp extends StatelessWidget {
    const AldujaApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        home: Scaffold(
                                backgroundColor: const Color(0xFF080B12),
                                        body: SafeArea(
                                                  child: Center(
                                                              child: Column(
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                          children: [
                                                                                                          const Text(
                                                                                                                            'الدجى',
                                                                                                                                              style: TextStyle(
                                                                                                                                                                  color: Color(0xFFD4AF5A),
                                                                                                                                                                                      fontSize: 52,
                                                                                                                                                                                                          fontWeight: FontWeight.bold,
                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                            const SizedBox(height: 20),

                                                                                                                                                                                                                                                                            const Text(
                                                                                                                                                                                                                                                                                              'بعض الحكايات لا تبدأ إلا حين يختفي الضوء.',
                                                                                                                                                                                                                                                                                                                textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                  style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                      color: Colors.white70,
                                                                                                                                                                                                                                                                                                                                                                          fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 45),

                                                                                                                                                                                                                                                                                                                                                                                                                                            ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: const Color(0xFFD4AF5A),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        foregroundColor: const Color(0xFF080B12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: const EdgeInsets.symmetric(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  horizontal: 35,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        vertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                shape: RoundedRectangleBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.circular(14),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'دخول إلى الدجى',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }